FROM ubuntu:15.10

# Update date to rebuild cached image
ENV REFRESHED_AT 2016-08-09


# Install dependencies
RUN apt-get update && apt-get install -y \
    autoconf \
    curl \
    python \
    nasm \
    libjpeg-progs \
    optipng \
    wget \
    gzip \
    tar \
    xvfb \
    libgtk-3-dev \
    libxslt1-dev \
    firefox \
    zip

# Install AWS command line tool
RUN \
  cd /tmp && \
  wget https://s3.amazonaws.com/aws-cli/awscli-bundle.zip && \
  unzip awscli-bundle.zip && \
  chmod 755 -R awscli-bundle && \
  ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws && \
  aws --version

# Install Node
# gpg keys listed at https://github.com/nodejs/node
RUN set -ex \
  && for key in \
    9554F04D7259F04124DE6B476D5A82AC7E37093B \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93 \
    FD3A5288F042B6850C66B31F09FE44734EB7990E \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
  ; do \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
  done

ENV NPM_CONFIG_LOGLEVEL info

ARG NODE_VERSION=fail
ENV NODE_VERSION ${NODE_VERSION}

RUN curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" \
  && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
  && gpg --verify SHASUMS256.txt.asc \
  && grep " node-v$NODE_VERSION-linux-x64.tar.gz\$" SHASUMS256.txt.asc | sha256sum -c - \
  && tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
  && rm "node-v$NODE_VERSION-linux-x64.tar.gz" SHASUMS256.txt.asc

# Needed to allow us to manually install a newer version of npm (3.10.5)
# via https://github.com/npm/npm/issues/9863#issuecomment-209194124
RUN cd $(npm root -g)/npm \
  && npm install fs-extra \
  && sed -i -e s/graceful-fs/fs-extra/ -e s/fs\.rename/fs\.move/ ./lib/utils/rename.js

# Manually install a newer version of npm (<3.10.4)
# (should be able to remove when npm -v is greater than npm 3.10.4 included with node)
#RUN npm install npm@latest -g

# Freeze npm version at 3.10.7 per issue with 3.10.8
# https://github.com/npm/npm/issues/14042
RUN npm install npm@3.10.7 -g

RUN npm install yarn

RUN mkdir -p /opt/appbuild

WORKDIR /opt/appbuild

COPY . /opt/appbuild
